Host: shinyorg.github.io
Title: Shiny.NET
SiteTitle: Documentation
SubTitle: Documentation
LinksUseHttps: true
TwitterHandle: shinydotnet
EditLink: => "https://github.com/shinyorg/shiny/edit/master/docs/input/" + doc.Source.GetRelativeInputPath()